### ISSUE TITLE
Unterstützung: coeamyd

### ISSUE THREAD

**Issue by coeamyd** [tscholze/xamarin-road-to-surface-duo#1]
Hallo Tobias!

Mein Name ist Christoph, ich bin freiberuflicher Software-Architekt und schon seit einigen Jahren auf der .NET Plattform unterwegs. Ich wollte mich schon immer mit Xamarin beschäftigen, habe aber nie die Zeit und Gelegenheit gefunden. Das Surface Duo gab mir nochmal einen neuen Anreiz, aber auch hier war bisher mein Elan noch nicht groß genug. Dein Projekt könnte mir endlich die Gelegenheit bieten, hier tätig zu werden. :-)

Wie gesagt, ich bin im .NET Umfeld an sich sehr erfahren (seit 2003). Die Backend-Logik, um die Artikel abzurufen, sollten für mich gar kein Thema sein. Mit XAML habe ich im Rahmen von WPF auch schon Erfahrung gesammelt, wobei ich definitiv kein Crack bin. Mein Fokus liegt dann doch eher auf Web-Technologien.

Ich würde mich gerne im Rahmen meiner zeitlichen Möglichkeiten als Unterstützer bei diesem Projekt melden. Vielleicht können wir uns ja mal persönlich unterhalten, wenn es für dich interessant klingt.

Beste Grüße,
Christoph

**Comment by tscholze** [comment]
Hallo @coeamyd,
dann hast du auf jeden Fall mehr Erfahrungen in .NET und C# als ich. Ist doch schon einmal ein super Start.

Da das Projekt ja vorallem Lust auf die Thematik machen soll, würde ich dich nur bitten, nicht alles auf den Experten-Niveau zu heben (dort wo es nicht unbedingt nötig ist).

Du kannst immer gern Issues öffnen. Bevor du aber Zeit in Pull requests investierst würde ich dich einfach bitten es mit mir abzustimmen da das Projekt in Sync auch mit den Artikeln auf Dr.Windows laufen sollte. Wäre ungut wenn die Artikel schon bei Erscheinen veraltete Code-Beispiele aus der App zeigen würden. :)

Das mit dem Threading klingt ideal nach einer ersten Fragen an dich. Aus meiner täglichen Arbeit mit iOS bin ich gewöhnt Network-Requests schön im Background laufen zu haben damit diese nicht die UI blockieren. Irgendwie fällt es mir aber schwer das in Xamarin.Forms genau so umzusetzen. Denke ich hier falsch? Löst man dies in der .NET Welt anders?

Danke schon einmal für deine Hilfe! :)

**Comment by coeamyd** [comment]
Ich sage mal so: Mit Xamarin / Mobilentwicklung bin ich blutiger Anfänger. Ich nehme an, da hast du mir sicher etwas voraus. Immerhin hatte ich Xamarin auf meinem alten Notebook schon installiert. Wirklich etwas damit gemacht hatte ich bisher noch nicht.

Ich habe die Installation auf meinem aktuellen Notebook nun nachgeholt und konnte die Applikation immerhin jetzt im Emulator starten. Die sieht ja schon mal ganz nett aus. :-)

Ich werde mir den aktuellen Code dann morgen mal zu Gemüte führen, und schauen, wo ich mich gewinnbringend einsetzen kann. Am besten wäre dann ja vermutlich, wenn ich mir hier einen eigenen Fork erstelle, oder sollen wir es lieber organisatorisch einfacher halten und auf Branches setzen?

**Comment by tscholze** [comment]
@coeamyd 
Kein Stress. :) Das Projekt ist auch für mich zum Lernen da.

Bitte. nutze folgendes vorgehen, dann passt es besser zum GitHub Workflow:

1. Forken
2. Feature-Branch machen
3. Pull request von deinem Feature Branch auf den master-Branch von diesem Repo stellen
4. Ich schau mir den PR an - eventuell hab ich Fragen oder man könnte was anders machen (is dann nicht böse gemeint)
5. Ich merge deinen Branch dann in diesen.

Ich habe keine festen Coding-Guidelines im Projekt hinterlegt, wäre nur toll wenn du einfach die was du im Projekt bisher siehst auch anwenden könntest. Das heißt `{` in neue Zeile oder keine `_` vor privaten Variablen, etc.

Ich freu mich!
