### ISSUE TITLE
Enhancement: Support hardware back button

### ISSUE THREAD

**Issue by tscholze** [tscholze/xamarin-road-to-surface-duo#3]
**At the moment**
Back button closes the app

**Future plan**
Back button should trigger a back navigation in the app itself. E.g. from detail back to list view

**Comment by coeamyd** [comment]
Is this still an issue? In my emulator, pressing back on the detail view leads me back to the list page.

**Comment by tscholze** [comment]
@coeamyd it breaks time by time. But in general it works already.

Thanks for testing it. I know that the feature could be broken now after the merge of the duo feature branch. There is still a lot to do.
